# Generated by Django 4.2.11 on 2025-04-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_alter_realtor_options_realtor_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='user',
        ),
    ]
